name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
      - "!**-alpha**"
jobs:
  build:
    run-on: ubuntu-latest
     - uses: actions/checkout@v1
        with:
          fetch-depth: 500
