name: CI

on: push

jobs:
    Lint-Project:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v1
         with:
           fetch-depth: 500
       - name: Lint lua files
         uses: nebularg/actions-luacheck@v1
         with:
           args: "--no-color -q"
           annotate: warning
 
    Deploy-Packages:
      if: startsWith(github.ref, 'refs/tags/')
      runs-on: ubuntu-latest
      needs: Lint-Project
      steps:
       - uses: actions/checkout@v1
         with:
           fetch-depth: 500
       - name: Upload locales strings to CurseForge
         run: ./CurseForge_UpldateTranslations.sh
         env:
           CF_API_KEY: ${{ secrets.CF_API_KEY }}
       - name: Create and uploat to curseforge
         uses: BigWigsMods/packager@master
         env:
           CF_API_KEY: ${{ secrets.CF_API_KEY }}
           GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
